name: course2024
channels:
   - conda-forge
dependencies:
   - ipython
   - jupyter
   - jupyterlab
   - nb_conda_kernels
   - numpy
   - matplotlib
   - pandas
   - xlrd
   - xlwt
   - cartopy
   - owslib
   - xarray
   - seaborn
   - netcdf4
   - dask
